SELECT
	*
FROM
	COMPANIES;

SELECT
	*
FROM
	PRICING;

SELECT
	*
FROM
	CUSTOMERS;

SELECT
	*
FROM
	LEADS;

SELECT
	*
FROM
	DEALS;

SELECT
	*
FROM
	CHURN;

SELECT
	*
FROM
	BUYER;

SELECT
	O.COMPANY_SIZE,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	COMPANY_SIZE IS NOT NULL
GROUP BY
	O.COMPANY_SIZE;

SELECT
	O.REGION,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	O.REGION IS NOT NULL
GROUP BY
	O.REGION
ORDER BY
	CONVERSION_RATE DESC;

SELECT
	O.INDUSTRY,
	COUNT(L.LEAD_ID) LEADS
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
WHERE
	INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	LEADS DESC;

SELECT
	O.INDUSTRY,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	O.REGION = 'LATAM'
	AND O.INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	CONVERSION_RATE DESC;

SELECT
	O.COMPANY_SIZE,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		2
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	O.REGION = 'LATAM'
	AND O.INDUSTRY = 'MarTech'
	AND O.COMPANY_SIZE IS NOT NULL
GROUP BY
	O.COMPANY_SIZE
ORDER BY
	CONVERSION_RATE DESC;

SELECT
	O.INDUSTRY,
	ROUND(
		SUM(
			CASE
				WHEN DEAL_STAGE = 'Closed Won' THEN 1
				ELSE 0
			END
		)::NUMERIC / NULLIF(
			SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Lost' THEN 1
					ELSE 0
				END
			) + SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Won' THEN 1
					ELSE 0
				END
			),
			0
		),
		4
	) WIN_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY;

SELECT
	O.REGION,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) LOST,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) + SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON_LOST,
	ROUND(
		SUM(
			CASE
				WHEN DEAL_STAGE = 'Closed Won' THEN 1
				ELSE 0
			END
		)::NUMERIC / NULLIF(
			SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Lost' THEN 1
					ELSE 0
				END
			) + SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Won' THEN 1
					ELSE 0
				END
			),
			0
		),
		4
	) WIN_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION IS NOT NULL
GROUP BY
	O.REGION
ORDER BY
	WIN_RATE DESC;

SELECT
	O.INDUSTRY,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) LOST,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) + SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON_LOST,
	ROUND(
		SUM(
			CASE
				WHEN DEAL_STAGE = 'Closed Won' THEN 1
				ELSE 0
			END
		)::NUMERIC / NULLIF(
			SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Lost' THEN 1
					ELSE 0
				END
			) + SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Won' THEN 1
					ELSE 0
				END
			),
			0
		),
		4
	) WIN_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION = 'MEA'
	AND O.INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	WIN_RATE DESC;

SELECT
	O.REGION,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	SUM(C.ARR_USD) REVENUE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON C.LEAD_ID = L.LEAD_ID
WHERE
	REGION IS NOT NULL
GROUP BY
	O.REGION
ORDER BY
	REVENUE DESC;

SELECT
	O.INDUSTRY,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE,
	SUM(C.ARR_USD) REVENUE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	O.INDUSTRY IS NOT NULL
	AND O.REGION = 'MEA'
GROUP BY
	O.INDUSTRY
ORDER BY
	REVENUE DESC;

SELECT
	O.INDUSTRY,
	D.PLAN_TIER,
	COUNT(D.PLAN_TIER) PLANS
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.INDUSTRY = 'LogisTech'
GROUP BY
	O.INDUSTRY,
	D.PLAN_TIER
ORDER BY
	PLANS;

WITH
	TOTAL_CUSTOMERS AS (
		SELECT
			O.REGION,
			COUNT(C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
		FROM
			CUSTOMERS C
			JOIN LEADS L ON C.LEAD_ID = L.LEAD_ID
			JOIN COMPANIES O ON L.COMPANY_ID = O.COMPANY_ID
		WHERE
			O.REGION IS NOT NULL
		GROUP BY
			O.REGION
	),
	CHURNED_CUSTOMERS AS (
		SELECT
			O.REGION,
			COUNT(H.CUSTOMER_ID) AS CHURNED_CUSTOMERS
		FROM
			CHURN H
			JOIN CUSTOMERS C ON H.CUSTOMER_ID = C.CUSTOMER_ID
			JOIN LEADS L ON C.LEAD_ID = L.LEAD_ID
			JOIN COMPANIES O ON L.COMPANY_ID = O.COMPANY_ID
		WHERE
			O.REGION IS NOT NULL
		GROUP BY
			O.REGION
	)
SELECT
	T.REGION,
	T.TOTAL_CUSTOMERS,
	COALESCE(C.CHURNED_CUSTOMERS, 0) AS CHURNED_CUSTOMERS,
	ROUND(
		COALESCE(C.CHURNED_CUSTOMERS, 0)::NUMERIC / NULLIF(T.TOTAL_CUSTOMERS, 0),
		4
	) AS CHURN_RATE
FROM
	TOTAL_CUSTOMERS T
	LEFT JOIN CHURNED_CUSTOMERS C ON T.REGION = C.REGION
ORDER BY
	CHURN_RATE DESC;

WITH
	TOTAL_CUSTOMERS AS (
		SELECT
			O.INDUSTRY,
			COUNT(C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
		WHERE
			REGION = 'North America'
			AND O.INDUSTRY IS NOT NULL
		GROUP BY
			O.INDUSTRY
	),
	CHURNED_CUSTOMERS AS (
		SELECT
			O.INDUSTRY,
			COUNT(H.CUSTOMER_ID) AS CHURNED_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
			JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
		WHERE
			O.REGION = 'North America'
			AND O.INDUSTRY IS NOT NULL
		GROUP BY
			O.INDUSTRY
	)
SELECT
	T.INDUSTRY,
	T.TOTAL_CUSTOMERS,
	H.CHURNED_CUSTOMERS,
	ROUND(
		(H.CHURNED_CUSTOMERS::NUMERIC) / NULLIF(T.TOTAL_CUSTOMERS, 0),
		4
	) CHURN_RATE
FROM
	TOTAL_CUSTOMERS T
	LEFT JOIN CHURNED_CUSTOMERS H ON T.INDUSTRY = H.INDUSTRY
ORDER BY
	CHURN_RATE DESC;

WITH
	TOTAL_CUSTOMERS AS (
		SELECT
			O.INDUSTRY,
			COUNT(C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
		WHERE
			REGION = 'MEA'
			AND O.INDUSTRY IS NOT NULL
		GROUP BY
			O.INDUSTRY
	),
	CHURNED_CUSTOMERS AS (
		SELECT
			O.INDUSTRY,
			COUNT(H.CUSTOMER_ID) AS CHURNED_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
			JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
		WHERE
			O.REGION = 'MEA'
			AND O.INDUSTRY IS NOT NULL
		GROUP BY
			O.INDUSTRY
	)
SELECT
	T.INDUSTRY,
	T.TOTAL_CUSTOMERS,
	H.CHURNED_CUSTOMERS,
	ROUND(
		COALESCE(H.CHURNED_CUSTOMERS, 0)::NUMERIC / NULLIF(T.TOTAL_CUSTOMERS, 0),
		4
	) AS CHURN_RATE
FROM
	TOTAL_CUSTOMERS T
	LEFT JOIN CHURNED_CUSTOMERS H ON T.INDUSTRY = H.INDUSTRY
ORDER BY
	CHURN_RATE DESC;

WITH
	TOTAL_CUSTOMERS AS (
		SELECT
			O.COMPANY_SIZE,
			COUNT(C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
		WHERE
			REGION = 'MEA'
			AND O.INDUSTRY = 'LogisTech'
		GROUP BY
			O.COMPANY_SIZE
	),
	CHURNED_CUSTOMERS AS (
		SELECT
			O.COMPANY_SIZE,
			COALESCE(COUNT(H.CUSTOMER_ID), 0) AS CHURNED_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
			JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
		WHERE
			O.REGION = 'MEA'
			AND O.INDUSTRY = 'LogisTech'
		GROUP BY
			O.COMPANY_SIZE
	)
SELECT
	T.COMPANY_SIZE,
	T.TOTAL_CUSTOMERS,
	COALESCE(H.CHURNED_CUSTOMERS, 0),
	ROUND(
		COALESCE(H.CHURNED_CUSTOMERS, 0)::NUMERIC / NULLIF(T.TOTAL_CUSTOMERS, 0),
		4
	) AS CHURN_RATE
FROM
	TOTAL_CUSTOMERS T
	LEFT JOIN CHURNED_CUSTOMERS H ON T.COMPANY_SIZE = H.COMPANY_SIZE
ORDER BY
	CHURN_RATE DESC;

WITH
	TOTAL_CUSTOMERS AS (
		SELECT
			D.PLAN_TIER,
			COUNT(C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
			JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
		WHERE
			REGION = 'MEA'
			AND O.INDUSTRY = 'LogisTech'
			AND O.COMPANY_SIZE = '1000+'
		GROUP BY
			D.PLAN_TIER
	),
	CHURNED_CUSTOMERS AS (
		SELECT
			D.PLAN_TIER,
			COALESCE(COUNT(H.CUSTOMER_ID), 0) AS CHURNED_CUSTOMERS
		FROM
			COMPANIES O
			JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
			JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
			JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
			JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
		WHERE
			O.REGION = 'MEA'
			AND O.INDUSTRY = 'LogisTech'
			AND O.COMPANY_SIZE = '1000+'
		GROUP BY
			D.PLAN_TIER
	)
SELECT
	T.PLAN_TIER,
	T.TOTAL_CUSTOMERS,
	COALESCE(H.CHURNED_CUSTOMERS, 0),
	ROUND(
		COALESCE(H.CHURNED_CUSTOMERS, 0)::NUMERIC / NULLIF(T.TOTAL_CUSTOMERS, 0),
		4
	) AS CHURN_RATE
FROM
	TOTAL_CUSTOMERS T
	LEFT JOIN CHURNED_CUSTOMERS H ON T.PLAN_TIER = H.PLAN_TIER
ORDER BY
	CHURN_RATE DESC;

SELECT
	O.INDUSTRY,
	D.PLAN_TIER,
	COUNT(D.PLAN_TIER) PLANS
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.INDUSTRY = 'LogisTech'
GROUP BY
	O.INDUSTRY,
	D.PLAN_TIER
ORDER BY
	PLANS;

SELECT
	O.COMPANY_TYPE,
	ROUND(
		AVG(
			L.DAYS_LEAD_TO_MQL + L.DAYS_MQL_TO_SQL + L.DAYS_SQL_TO_OPPORTUNITY + L.DAYS_OPPORTUNITY_TO_CLOSE
		),
		2
	) AVG_DAYS_TO_CONVERT
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
GROUP BY
	O.COMPANY_TYPE
ORDER BY
	AVG_DAYS_TO_CONVERT DESC;

SELECT
	O.REGION,
	ROUND(
		AVG(
			L.DAYS_LEAD_TO_MQL + L.DAYS_MQL_TO_SQL + L.DAYS_SQL_TO_OPPORTUNITY + L.DAYS_OPPORTUNITY_TO_CLOSE
		),
		2
	) AVG_DAYS_TO_CONVERT
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
WHERE
	REGION IS NOT NULL
GROUP BY
	O.REGION
ORDER BY
	AVG_DAYS_TO_CONVERT;

SELECT
	O.INDUSTRY,
	ROUND(
		AVG(
			L.DAYS_LEAD_TO_MQL + L.DAYS_MQL_TO_SQL + L.DAYS_SQL_TO_OPPORTUNITY + L.DAYS_OPPORTUNITY_TO_CLOSE
		),
		2
	) AVG_DAYS_TO_CONVERT
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
WHERE
	REGION = 'North America'
	AND O.INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	AVG_DAYS_TO_CONVERT;

SELECT
	O.COMPANY_SIZE,
	ROUND(
		AVG(
			L.DAYS_LEAD_TO_MQL + L.DAYS_MQL_TO_SQL + L.DAYS_SQL_TO_OPPORTUNITY + L.DAYS_OPPORTUNITY_TO_CLOSE
		),
		2
	) AVG_DAYS_TO_CONVERT
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
WHERE
	REGION = 'North America'
	AND O.INDUSTRY = 'LegalTech'
	AND COMPANY_SIZE IS NOT NULL
GROUP BY
	O.COMPANY_SIZE
ORDER BY
	AVG_DAYS_TO_CONVERT;

SELECT
	D.PLAN_TIER,
	ROUND(
		AVG(
			L.DAYS_LEAD_TO_MQL + L.DAYS_MQL_TO_SQL + L.DAYS_SQL_TO_OPPORTUNITY + L.DAYS_OPPORTUNITY_TO_CLOSE
		),
		2
	) AVG_DAYS_TO_CONVERT
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	REGION = 'North America'
	AND O.INDUSTRY = 'LegalTech'
	AND COMPANY_SIZE = '51-200'
	AND D.PLAN_TIER IS NOT NULL
GROUP BY
	D.PLAN_TIER
ORDER BY
	AVG_DAYS_TO_CONVERT;

SELECT
	O.INDUSTRY,
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AVG_DEAL_VALUE_ANNUAL_USD
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.INDUSTRY IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	AVG_DEAL_VALUE_ANNUAL_USD DESC;

SELECT
	O.REGION,
	COUNT(D.DEAL_ID) AS NUM_DEALS,
	SUM(D.DEAL_VALUE_ANNUAL_USD),
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AVG_DEAL_VALUE_ANNUAL_USD
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION IS NOT NULL
	AND D.DEAL_VALUE_ANNUAL_USD IS NOT NULL
GROUP BY
	O.REGION
ORDER BY
	AVG_DEAL_VALUE_ANNUAL_USD DESC;

SELECT
	O.INDUSTRY,
	COUNT(D.DEAL_ID) AS NUM_DEALS,
	SUM(D.DEAL_VALUE_ANNUAL_USD),
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AVG_DEAL_VALUE_ANNUAL_USD
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION = 'North America'
	AND O.INDUSTRY IS NOT NULL
	AND D.DEAL_VALUE_ANNUAL_USD IS NOT NULL
GROUP BY
	O.INDUSTRY
ORDER BY
	AVG_DEAL_VALUE_ANNUAL_USD DESC;

SELECT
	O.COMPANY_SIZE,
	COUNT(D.DEAL_ID) AS NUM_DEALS,
	SUM(D.DEAL_VALUE_ANNUAL_USD),
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AVG_DEAL_VALUE_ANNUAL_USD
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION = 'North America'
	AND O.INDUSTRY = 'HealthTech'
	AND O.COMPANY_SIZE IS NOT NULL
	AND D.DEAL_VALUE_ANNUAL_USD IS NOT NULL
GROUP BY
	O.COMPANY_SIZE
ORDER BY
	AVG_DEAL_VALUE_ANNUAL_USD DESC;

SELECT
	D.PLAN_TIER,
	COUNT(D.DEAL_ID) AS NUM_DEALS,
	SUM(D.DEAL_VALUE_ANNUAL_USD),
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AVG_DEAL_VALUE_ANNUAL_USD
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION = 'North America'
	AND O.INDUSTRY = 'HealthTech'
	AND O.COMPANY_SIZE = '501-1000'
	AND D.PLAN_TIER IS NOT NULL
	AND D.DEAL_VALUE_ANNUAL_USD IS NOT NULL
GROUP BY
	D.PLAN_TIER
ORDER BY
	AVG_DEAL_VALUE_ANNUAL_USD DESC;

WITH
	BEST_CUSTOMERS AS (
		SELECT
			*
		FROM
			CUSTOMERS
		WHERE
			ARR_USD >= (
				SELECT
					PERCENTILE_CONT(0.75) WITHIN GROUP (
						ORDER BY
							ARR_USD
					)
				FROM
					CUSTOMERS
			)
	)
SELECT
	UNNEST(STRING_TO_ARRAY(C.TECH_STACK, '; ')) AS TOOL,
	COUNT(*) AS FREQUENCY
FROM
	COMPANIES C
	JOIN LEADS L ON C.COMPANY_ID = L.COMPANY_ID
	JOIN BEST_CUSTOMERS BC ON L.LEAD_ID = BC.LEAD_ID
GROUP BY
	TOOL
ORDER BY
	FREQUENCY DESC;

SELECT
	(LEAD_SOURCE),
	COUNT(LEAD_ID) LEADS
FROM
	LEADS
GROUP BY
	LEAD_SOURCE
ORDER BY
	LEADS DESC;

SELECT
	L.LEAD_SOURCE,
	COUNT(L.LEAD_ID) TOTAL_LEADS,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE,
	SUM(C.ARR_USD) REVENUE
FROM
	LEADS L
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
GROUP BY
	L.LEAD_SOURCE
ORDER BY
	REVENUE DESC;

SELECT
	UTM_CAMPAIGN,
	COUNT(FUNNEL_STAGE) CONVERTED_LEADS
FROM
	LEADS
WHERE
	FUNNEL_STAGE <> 'Lead'
	AND FUNNEL_STAGE <> 'Unqualified'
	AND UTM_CAMPAIGN IS NOT NULL
GROUP BY
	UTM_CAMPAIGN
ORDER BY
	CONVERTED_LEADS DESC;

SELECT
	L.UTM_CAMPAIGN,
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AS AVG_WON_DEAL_VALUE
FROM
	LEADS L
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	D.DEAL_STAGE = 'Closed Won'
	AND UTM_CAMPAIGN IS NOT NULL
GROUP BY
	L.UTM_CAMPAIGN
ORDER BY
	AVG_WON_DEAL_VALUE DESC;

WITH
	LEAD_STAGES AS (
		SELECT
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE = 'Lead'
			) AS LEADS,
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE = 'MQL'
			) AS MQLS,
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE = 'SQL'
			) AS SQLS
		FROM
			LEADS
	),
	DEAL_STAGES AS (
		SELECT
			COUNT(*) FILTER (
				WHERE
					DEAL_STAGE IN ('Proposal Sent', 'Negotiation', 'Contract Sent')
			) AS OPPORTUNITIES,
			COUNT(*) FILTER (
				WHERE
					DEAL_STAGE = 'Closed Won'
			) AS CLOSED_WON
		FROM
			DEALS
	)
SELECT
	LEADS,
	MQLS,
	SQLS,
	OPPORTUNITIES,
	CLOSED_WON,
	ROUND(MQLS::NUMERIC / NULLIF(LEADS, 0), 4) AS LEAD_TO_MQL_RATE,
	ROUND(SQLS::NUMERIC / NULLIF(MQLS, 0), 4) AS MQL_TO_SQL_RATE,
	ROUND(OPPORTUNITIES::NUMERIC / NULLIF(SQLS, 0), 4) AS SQL_TO_OPPORTUNITY_RATE,
	ROUND(CLOSED_WON::NUMERIC / NULLIF(OPPORTUNITIES, 0), 4) AS OPPORTUNITY_TO_CLOSED_WON_RATE
FROM
	LEAD_STAGES
	CROSS JOIN DEAL_STAGES;

SELECT
	LEAD_SOURCE,
	COUNT(*) AS TOTAL_LEADS,
	COUNT(*) FILTER (
		WHERE
			FUNNEL_STAGE IN ('MQL', 'SQL')
	) AS MQLS,
	COUNT(*) FILTER (
		WHERE
			FUNNEL_STAGE = 'SQL'
	) AS SQLS,
	ROUND(
		(
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE IN ('MQL', 'SQL')
			)
		)::NUMERIC / COUNT(*),
		4
	) AS LEAD_TO_MQL_RATE,
	ROUND(
		(
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE = 'SQL'
			)
		)::NUMERIC / NULLIF(
			COUNT(*) FILTER (
				WHERE
					FUNNEL_STAGE IN ('MQL', 'SQL')
			),
			0
		),
		4
	) AS MQL_TO_SQL_RATE
FROM
	LEADS
GROUP BY
	LEAD_SOURCE
ORDER BY
	LEAD_TO_MQL_RATE ASC;

SELECT
	ROUND(AVG(DAYS_LEAD_TO_MQL), 2) AS AVG_DAYS_LEAD_TO_MQL,
	ROUND(AVG(DAYS_MQL_TO_SQL), 2) AS AVG_DAYS_MQL_TO_SQL,
	ROUND(AVG(DAYS_SQL_TO_OPPORTUNITY), 2) AS AVG_DAYS_SQL_TO_OPPORTUNITY,
	ROUND(AVG(DAYS_OPPORTUNITY_TO_CLOSE), 2) AS AVG_DAYS_OPPORTUNITY_TO_CLOSE
FROM
	LEADS;

SELECT
	O.COMPANY_SIZE,
	O.INDUSTRY,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	COMPANY_SIZE IS NOT NULL
	AND O.INDUSTRY IS NOT NULL
GROUP BY
	O.COMPANY_SIZE,
	O.INDUSTRY
ORDER BY
	CONVERSION_RATE DESC;

SELECT
	O.COMPANY_SIZE,
	O.INDUSTRY,
	ROUND(
		COUNT(C.CUSTOMER_ID)::NUMERIC / COUNT(L.LEAD_ID),
		4
	) CONVERSION_RATE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	LEFT JOIN CUSTOMERS C ON L.LEAD_ID = C.LEAD_ID
WHERE
	O.REGION = 'LATAM'
	AND COMPANY_SIZE IS NOT NULL
	AND O.INDUSTRY IS NOT NULL
GROUP BY
	O.COMPANY_SIZE,
	O.INDUSTRY
ORDER BY
	CONVERSION_RATE DESC;

SELECT
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) AS AVG_DEAL_VALUE
FROM
	COMPANIES O
	JOIN LEADS L ON O.COMPANY_ID = L.COMPANY_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	O.REGION = 'LATAM'
	AND O.COMPANY_SIZE = '1-10'
	AND O.INDUSTRY = 'MarTech';

SELECT DISTINCT
	(ASSIGNED_REP),
	COUNT(DEAL_STAGE) DEALS
FROM
	LEADS L
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	DEAL_STAGE = 'Closed Won'
	AND ASSIGNED_REP IS NOT NULL
GROUP BY
	ASSIGNED_REP
ORDER BY
	DEALS DESC;

SELECT DISTINCT
	(L.ASSIGNED_REP),
	ROUND(AVG(D.DEAL_VALUE_ANNUAL_USD), 2) DEAL_VALUE,
	SUM(C.ARR_USD) REVENUE
FROM
	CUSTOMERS C
	JOIN LEADS L ON C.LEAD_ID = L.LEAD_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	ASSIGNED_REP IS NOT NULL
	AND DEAL_STAGE = 'Closed Won'
GROUP BY
	ASSIGNED_REP
ORDER BY
	REVENUE DESC;

SELECT
	L.ASSIGNED_REP,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) LOST,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) + SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) WON_LOST,
	ROUND(
		SUM(
			CASE
				WHEN DEAL_STAGE = 'Closed Won' THEN 1
				ELSE 0
			END
		)::NUMERIC / NULLIF(
			SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Lost' THEN 1
					ELSE 0
				END
			) + SUM(
				CASE
					WHEN DEAL_STAGE = 'Closed Won' THEN 1
					ELSE 0
				END
			),
			0
		),
		4
	) WIN_RATE
FROM
	LEADS L
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	L.ASSIGNED_REP IS NOT NULL
GROUP BY
	L.ASSIGNED_REP
ORDER BY
	WIN_RATE DESC;

SELECT
	L.ASSIGNED_REP,
	D.DEAL_STAGE,
	ROUND(AVG(D.CLOSE_DATE::DATE - L.CREATED_DATE::DATE), 2) AS DEAL_VELOCITY
FROM
	LEADS L
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	DEAL_STAGE = 'Closed Won'
	AND L.ASSIGNED_REP IS NOT NULL
GROUP BY
	D.DEAL_STAGE,
	L.ASSIGNED_REP
ORDER BY
	DEAL_VELOCITY;

SELECT
	L.ASSIGNED_REP,
	ROUND(AVG(D.DISCOUNT_PCT), 2) DISCOUNT
FROM
	LEADS L
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
WHERE
	L.ASSIGNED_REP IS NOT NULL
GROUP BY
	L.ASSIGNED_REP
ORDER BY
	DISCOUNT ASC;

SELECT
	SUM(MRR_USD) AS TOTAL_MRR,
	SUM(ARR_USD) AS TOTAL_ARR
FROM
	CUSTOMERS;

SELECT
	ROUND(AVG(ARR_USD), 2) AS AVG_ARR_PER_CUSTOMER
FROM
	CUSTOMERS;

SELECT
	C.PLAN_TIER,
	SUM(ARR_USD) TOTAL_REVENUE
FROM
	CUSTOMERS C
WHERE
	PLAN_TIER IS NOT NULL
GROUP BY
	C.PLAN_TIER
ORDER BY
	TOTAL_REVENUE DESC;

SELECT DISTINCT
	(D.DEAL_TYPE),
	SUM(C.ARR_USD) REVENUE
FROM
	CUSTOMERS C
	JOIN LEADS L ON C.LEAD_ID = L.LEAD_ID
	JOIN DEALS D ON L.LEAD_ID = D.LEAD_ID
GROUP BY
	DEAL_TYPE
ORDER BY
	REVENUE DESC;

SELECT
	COUNT(C.CUSTOMER_ID),
	COUNT(H.CUSTOMER_ID),
	ROUND(
		COUNT(H.CUSTOMER_ID)::NUMERIC / COUNT(C.CUSTOMER_ID),
		4
	) CHURN_RATE
FROM
	CUSTOMERS C
	LEFT JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID;

SELECT
	MIN(C.CONTRACT_START_DATE) AS EARLIEST_CONTRACT_START,
	MAX(C.CONTRACT_START_DATE) AS LATEST_CONTRACT_START,
	MIN(H.CHURN_DATE) AS EARLIEST_CHURN_DATE,
	MAX(H.CHURN_DATE) AS LATEST_CHURN_DATE
FROM
	CUSTOMERS C
	LEFT JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID;

SELECT
	C.PLAN_TIER,
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	COUNT(H.CUSTOMER_ID) TOTAL_CHURN,
	ROUND(
		COUNT(H.CUSTOMER_ID)::NUMERIC / COUNT(C.CUSTOMER_ID),
		4
	) CHURN_RATE
FROM
	CUSTOMERS C
	LEFT JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
WHERE
	C.PLAN_TIER IS NOT NULL
GROUP BY
	C.PLAN_TIER
ORDER BY
	CHURN_RATE DESC;

SELECT
	H.CHURN_REASON,
	COUNT(H.CUSTOMER_ID) TOTAL_CHURN
FROM
	CHURN H
WHERE
	H.CHURN_REASON IS NOT NULL
GROUP BY
	H.CHURN_REASON
ORDER BY
	TOTAL_CHURN DESC;

SELECT DISTINCT
	(C.HEALTH_STATUS),
	COUNT(C.CUSTOMER_ID) TOTAL_CUSTOMERS,
	COUNT(H.CUSTOMER_ID) TOTAL_CHURN,
	ROUND(
		COUNT(H.CUSTOMER_ID)::NUMERIC / COUNT(C.CUSTOMER_ID),
		4
	) CHURN_RATE
FROM
	CUSTOMERS C
	LEFT JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID
GROUP BY
	C.HEALTH_STATUS
ORDER BY
	CHURN_RATE DESC;

SELECT DISTINCT
	(WIN_BACK_ATTEMPTED),
	COUNT(WIN_BACK_ATTEMPTED)
FROM
	CHURN
GROUP BY
	WIN_BACK_ATTEMPTED;

SELECT DISTINCT
	(WIN_BACK_ATTEMPTED),
	WIN_BACK_SUCCESSFUL,
	COUNT(WIN_BACK_SUCCESSFUL) SUCCESSFUL
FROM
	CHURN
WHERE
	WIN_BACK_ATTEMPTED = TRUE
GROUP BY
	WIN_BACK_ATTEMPTED,
	WIN_BACK_SUCCESSFUL;

SELECT
	SUM(WEIGHTED_VALUE_USD) WEIGHTED_VALUE_USD
FROM
	DEALS
WHERE
	DEAL_STAGE IN ('Proposal Sent', 'Negotiation', 'Contract Sent');

SELECT
	COMPETITOR,
	COUNT(LOSS_REASON) LOSES
FROM
	DEALS
WHERE
	LOSS_REASON = 'Went with competitor'
	AND COMPETITOR IS NOT NULL
GROUP BY
	COMPETITOR
ORDER BY
	LOSES DESC;

SELECT
	COMPETITOR,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Won' THEN 1
			ELSE 0
		END
	) AS WON_DEALS,
	SUM(
		CASE
			WHEN DEAL_STAGE = 'Closed Lost' THEN 1
			ELSE 0
		END
	) AS LOST_DEALS,
	ROUND(
		SUM(
			CASE
				WHEN DEAL_STAGE = 'Closed Won' THEN 1
				ELSE 0
			END
		)::NUMERIC / NULLIF(
			SUM(
				CASE
					WHEN DEAL_STAGE IN ('Closed Won', 'Closed Lost') THEN 1
					ELSE 0
				END
			),
			0
		),
		4
	) AS WIN_RATE
FROM
	DEALS
WHERE
	COMPETITOR IS NOT NULL
GROUP BY
	COMPETITOR
ORDER BY
	WIN_RATE DESC;

SELECT DISTINCT
	(AUTO_RENEW),
	SUM(ARR_USD) REVENUE
FROM
	CUSTOMERS
WHERE
	AUTO_RENEW = TRUE
GROUP BY
	AUTO_RENEW
ORDER BY
	REVENUE DESC;

SELECT
	ROUND(
		COUNT(*) FILTER (
			WHERE
				RENEWAL_DATE BETWEEN CURRENT_DATE AND CURRENT_DATE  + INTERVAL '90 days'
		)::NUMERIC / COUNT(*),
		4
	) AS PCT_DUE_FOR_RENEWAL_90_DAYS
FROM
	CUSTOMERS;

SELECT
	HEALTH_STATUS,
	AUTO_RENEW,
	COUNT(*) AS CUSTOMERS_DUE_FOR_RENEWAL
FROM
	CUSTOMERS
WHERE
	RENEWAL_DATE BETWEEN CURRENT_DATE AND CURRENT_DATE  + INTERVAL '90 days'
GROUP BY
	HEALTH_STATUS,
	AUTO_RENEW
ORDER BY
	CUSTOMERS_DUE_FOR_RENEWAL DESC;

SELECT
	HEALTH_STATUS,
	SUM(ARR_USD) REVENUE
FROM
	CUSTOMERS
GROUP BY
	HEALTH_STATUS
ORDER BY
	REVENUE DESC;

SELECT
	ROUND(
		(
			SUM(C.ARR_USD) + SUM(C.EXPANSION_REVENUE_USD) - SUM(COALESCE(H.CHURNED_ARR_USD, 0))
		) / NULLIF(SUM(C.ARR_USD), 0) * 100,
		2
	) AS NRR
FROM
	CUSTOMERS C
	LEFT JOIN CHURN H ON C.CUSTOMER_ID = H.CUSTOMER_ID;

	WITH
LEAD_STAGES AS (
    SELECT
        COUNT(*) FILTER (WHERE FUNNEL_STAGE = 'Lead') AS LEADS,
        COUNT(*) FILTER (WHERE FUNNEL_STAGE = 'MQL') AS MQLS,
        COUNT(*) FILTER (WHERE FUNNEL_STAGE = 'SQL') AS SQLS
    FROM LEADS
),
DEAL_STAGES AS (
    SELECT
        COUNT(*) FILTER (
            WHERE DEAL_STAGE IN ('Proposal Sent', 'Negotiation', 'Contract Sent')
        ) AS OPPORTUNITIES,
        COUNT(*) FILTER (
            WHERE DEAL_STAGE = 'Closed Won'
        ) AS CLOSED_WON
    FROM DEALS
)

SELECT 'Leads' AS STAGE, LEADS AS COUNT
FROM LEAD_STAGES

UNION ALL

SELECT 'MQLs', MQLS
FROM LEAD_STAGES

UNION ALL

SELECT 'SQLs', SQLS
FROM LEAD_STAGES

UNION ALL

SELECT 'Opportunities', OPPORTUNITIES
FROM DEAL_STAGES

UNION ALL

SELECT 'Closed Won', CLOSED_WON
FROM DEAL_STAGES;